/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "hardcoded-bg": "var(--hardcoded-bg)",
        "hardcoded-border": "var(--hardcoded-border)",
        "surface-dim": "var(--surface-dim)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface": "var(--surface)",
        "surface-container-highest": "var(--surface-container-highest)",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary": "var(--on-secondary)",
        "inverse-surface": "var(--inverse-surface)",
        "on-error-container": "var(--on-error-container)",
        "outline": "var(--outline)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-tint": "var(--surface-tint)",
        "surface-container": "var(--surface-container)",
        "on-tertiary": "var(--on-tertiary)",
        "tertiary": "var(--tertiary)",
        "on-error": "var(--on-error)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "primary-container": "var(--primary-container)",
        "primary": "var(--primary)",
        "error": "var(--error)",
        "primary-fixed": "var(--primary-fixed)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "on-primary-container": "var(--on-primary-container)",
        "tertiary-container": "var(--tertiary-container)",
        "outline-variant": "var(--outline-variant)",
        "background": "var(--background)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-background": "var(--on-background)",
        "surface-variant": "var(--surface-variant)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "secondary": "var(--secondary)",
        "surface-bright": "var(--surface-bright)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-surface": "var(--on-surface)",
        "error-container": "var(--error-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "secondary-container": "var(--secondary-container)",
        "on-primary": "var(--on-primary)"
      },
      spacing: {
        "panel-inspector": "320px",
        "gap-md": "16px",
        "unit": "4px",
        "gap-lg": "24px",
        "gap-xs": "4px",
        "panel-sidebar": "260px",
        "gutter": "16px",
        "margin-page": "24px",
        "gap-sm": "8px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Geist"],
        "headline-md": ["Geist"],
        "body-lg": ["Inter"],
        "display": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "headline-lg": ["Geist"],
        "label-sm": ["Geist"]
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "display": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
